#!/bin/bash

PKG_NAME="wireguard"
INST_DIR="/tmp/_${PKG_NAME}"
PKG_DIR="/tmp/_${PKG_NAME}_pkg"
PKG_DEST="/image/packages"

PrepareDirs(){
	for dir in $INST_DIR $PKG_DIR; do
		rm -rf "$dir"
	done
	for dir in $INST_DIR $PKG_DIR $PKG_DEST; do
		mkdir -p "$dir"
	done
}

InstallWG(){
	DESTDIR=${INST_DIR} make install
}

GenerateINFO(){
	synology/INFO.sh > INFO
	cp INFO "$PKG_DIR"
}

InstallSynologyConfig(){
	cp -r synology/scripts/ "$PKG_DIR" 
	cp -r synology/conf/ "$PKG_DIR"
}

MakePackage(){
	source /pkgscripts/include/pkg_util.sh
	pkg_make_package $INST_DIR $PKG_DIR
	pkg_make_spk $PKG_DIR $PKG_DEST
}

main(){
	PrepareDirs
	InstallWG
	GenerateINFO
	InstallSynologyConfig
	MakePackage
}

main "$@"
